@url = "http://localhost:3700/"

GET http://localhost:3700 HTTP/1.1
####################################

POST http://localhost:3700 HTTP/1.1
Content-Type: application/json

{
    "name": "CHuku241",
    "email": "Chuku"
}
###

GET http://localhost:3700/c4098b55-cb69-4795-bea2-d250683dbb05 HTTP/1.1

#####################
PUT http://localhost:3700/c4098b55-cb69-4795-bea2-d250683dbb05 HTTP/1.1
Content-Type: application/json

{
    "name": "NweCHuku1",
    "email": "NweeChuku"
}

###
DELETE http://localhost:3700/beddf587-159e-4e22-8baf-5f28d47f1c12 HTTP/1.1