@url = "http://localhost:3700/"

GET http://localhost:3700 HTTP/1.1
####################################

POST http://localhost:3700 HTTP/1.1
Content-Type: application/json

{
    "name": "CHuku1",
    "email": "Chuku"
}
###

GET http://localhost:3700/6f67a069-488f-44b5-a38d-8c8ddbd28786 HTTP/1.1

#####################
PUT http://localhost:3700 HTTP/1.1
Content-Type: application/json

{
    "name": "CHuku1",
    "email": "Chuku"
}