@url = "http://localhost:3700/"

GET http://localhost:3700 HTTP/1.1
####################################

POST http://localhost:3700 HTTP/1.1
Content-Type: application/json

{
    "name": "CHuku1",
    "email": "Chuku"
}
###

GET http://localhost:3700/c4098b55-cb69-4795-bea2-d250683dbb05 HTTP/1.1

#####################
PUT http://localhost:3700/c4098b55-cb69-4795-bea2-d250683dbb05 HTTP/1.1
Content-Type: application/json

{
    "name": "NweCHuku1",
    "email": "NweeChuku"
}